groups:
    - zsh
    - developer
recipes:
    global:
        - dotfiles::sshconfig
    mac_os_x:
        - applications::omnigraffle
        - applications::launchrocket
        - sudoalt::default
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::set_computer_name
attributes:
    dotfiles:
        vimusers:
            - root
            - jkeroes
        kdeploy:
            hostname: dev
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
    git:
        name: Joshua Keroes
        email: joshua@keroes.com
    osxdefaults:
        computername: soma
    authorization:
        sudo:
            users:
                - jkeroes
            passwordless: true
            include_sudoers_d: true
    homebrewalt:
        apps:
            - autojump
            - coreutils
            - curl
            - denyhosts
            - expat
            - flac
            - geoip
            - htop
            - iftop
            - ipcalc
            - jpeg
            - ngrep
            - nmap
            - parallel
            - pixman
            - pkg-config
            - proctools
            - pstree
            - readline
            - rlwrap
            - sqlite
            - ssh-copy-id
            - tmux
            - tree
            - unrar
            - vnstat
            - watch
        cask_apps:
            - adium
            - all2mp3
            - anki
            - bartender
            - dropbox
            - evernote
            - flip4mac
            - flux
            - gemini
            - google-chrome
            - google-drive
            - google-earth
            - google-hangouts
            - google-music-manager
            - google-quick-search-box
            - google-refine
            - google-web-designer
            - grandperspective
            - hazel
            - keyremap4macbook
            - little-snitch
            - menumeters
            - mou
            - mysql-workbench
            - navicat-mysql
            - onepassword
            - pckeyboardhack
            - quicksilver
            - rescuetime
            - skitch
            - spotify
            - sshfs
            - the-unarchiver
            - time-out
            - transmit
            - typinator
            - vagrant
            - virtualbox
            - vlc
            - vmware-fusion

# ssh-add -K $ssh-keys to store in OSX keychain

# appstore
# growl
# dbvisualizer
# oxygen
